# Hexo 配置文件
## 文档: https://hexo.io/docs/configuration.html

# 网站
title: "符号看象限"
subtitle: ""
description: "博客、分享、经验、教程"
keywords: "御坂网络工作室,博客,分享,经验,教程"
author: "YangRucheng"
language: "zh-CN"
timezone: "Asia/Shanghai"
favicon:
  small: /favicon.ico

# 链接
url: https://blog.yangrucheng.top
permalink: posts/:year:month/:hash/
pretty_urls:
  trailing_index: false
  trailing_html: false

# 目录
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# 文章
new_post_name: :title.md
default_layout: post
post_meta:
  page:
    date_type: created # created or updated or both 主頁文章日期是創建日或者更新日或都顯示
    date_format: date # date/relative 顯示日期還是相對日期
    categories: true # true or false 主頁是否顯示分類
    tags: true # true or false 主頁是否顯示標籤
  post:
    date_type: both # created or updated or both 文章頁日期是創建日或者更新日或都顯示
    date_format: relative # date/relative 顯示日期還是相對日期
    categories: true # true or false 文章頁是否顯示分類
    tags: true # true or false 文章頁是否顯示標籤

# 日期时间格式
date_format: YYYY-MM-DD
time_format: HH:mm
updated_option: "mtime"

# 扩展
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: "butterfly"

# 访问统计
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true
