- class_name: 音乐
  class_desc: 未完成
  link_list:
    - name: micoの博客
      link: https://csuer411.github.io
      avatar: https://github.com/csuer411/img/blob/master/animegirl/IMG_20221012_171725.jpg
      descr: 夜阑听雨眠
    - name: 万事屋科技
      link: https://bbs.idceo.cn/
      avatar: https://bbs.idceo.cn/upload/admin/202301/15/1_1673793486_sHklepBLam.jpg
      descr: 刘思科大佬进驻
