name: Hexo Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cache Node Modules
        # 设置包缓存目录，避免每次下载
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Hexo Dependencies
        # 下载 hexo-cli 脚手架及相关安装包
        run: |
          npm install -g hexo-cli
          npm install

      - name: Generate Hexo HTML Files
        # 编译 markdown 文件
        run: |
          hexo clean
          hexo generate

      - name: Deploy Hexo Blog to Pages Branch
        # 将编译后的博客文件推送到指定仓库
        run: |
          cd ./public && git init && git add .
          git config user.name "YangRucheng"
          git config user.email "admin@yangrucheng.top"
          git add .
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          directory: ./public
          branch: pages
          github_token: ${{ secrets.ACCESS_TOKEN }}
          force_with_lease: true
