name: Hexo Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        # 代码检查
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Node.js
        # 安装Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      
      - name: Setup Python
        # 安装Python, 并缓存包
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Handle Markdown
        # 预处理 markdown 文件
        run: |
          python3 main.py

      - name: Cache Node Modules
        # 设置包缓存目录，避免每次下载
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Hexo Dependencies
        # 下载 hexo-cli 脚手架及相关安装包
        run: |
          npm install -g hexo-cli
          npm install

      - name: Generate Hexo HTML Files
        # 编译 markdown 文件
        run: |
          hexo clean
          hexo generate

      - name: Deploy Hexo Blog to Pages Branch
        # 将编译后的博客文件推送到指定仓库
        env:
          GITHUB_REPO: github.com/YangRucheng/Blog-Hexo
        run: |
          cd ./public && git init && git add .
          git branch -m pages
          git config user.name "YangRucheng"
          git config user.email "admin@yangrucheng.top"
          git add .
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"

          git push --force --quiet "https://${{ secrets.ACCESS_TOKEN }}@$GITHUB_REPO" pages:pages

